
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:cherry_blossom_grove", "biomesoplenty:orchard", "biomesoplenty:snowy_maple_woods", "biomesoplenty:bamboo_grove", "biomesoplenty:rainforest", "minecraft:old_growth_birch_forest", "biomesoplenty:fir_clearing", "biomesoplenty:bog", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:grove", "minecraft:swamp", "biomesoplenty:field", "biomesoplenty:woodland", "biomesoplenty:rainbow_hills", "biomesoplenty:maple_woods", "biomesoplenty:mystic_grove", "biomesoplenty:muskeg", "minecraft:sparse_jungle", "biomesoplenty:wetland", "biomesoplenty:highland_moor", "biomesoplenty:lavender_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:forested_field", "biomesoplenty:jade_cliffs", "biomesoplenty:snowy_fir_clearing", "minecraft:forest", "biomesoplenty:bayou", "biomesoplenty:marsh", "biomesoplenty:coniferous_forest", "biomesoplenty:ominous_woods", "minecraft:old_growth_pine_taiga", "biomesoplenty:dead_forest", "biomesoplenty:redwood_forest", "minecraft:birch_forest", "minecraft:taiga", "minecraft:old_growth_spruce_taiga", "biomesoplenty:floodplain", "minecraft:snowy_taiga", "minecraft:windswept_forest", "biomesoplenty:old_growth_dead_forest", "biomesoplenty:old_growth_woodland", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch", "biomesoplenty:boreal_forest"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 8
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:cherry_blossom_grove", "biomesoplenty:orchard", "biomesoplenty:snowy_maple_woods", "biomesoplenty:bamboo_grove", "biomesoplenty:rainforest", "minecraft:old_growth_birch_forest", "biomesoplenty:fir_clearing", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:grove", "biomesoplenty:field", "biomesoplenty:woodland", "biomesoplenty:rainbow_hills", "biomesoplenty:maple_woods", "biomesoplenty:mystic_grove", "minecraft:sparse_jungle", "biomesoplenty:wetland", "biomesoplenty:lavender_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:forested_field", "biomesoplenty:jade_cliffs", "biomesoplenty:snowy_fir_clearing", "minecraft:forest", "biomesoplenty:coniferous_forest", "biomesoplenty:ominous_woods", "minecraft:old_growth_pine_taiga", "biomesoplenty:dead_forest", "biomesoplenty:redwood_forest", "minecraft:birch_forest", "minecraft:taiga", "minecraft:old_growth_spruce_taiga", "minecraft:snowy_taiga", "minecraft:windswept_forest", "biomesoplenty:old_growth_dead_forest", "biomesoplenty:old_growth_woodland", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch", "biomesoplenty:boreal_forest"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 12.5

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:cherry_blossom_grove", "biomesoplenty:snowy_maple_woods", "undergarden:mushroom_bog", "biomesoplenty:bamboo_grove", "biomesoplenty:bog", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:grove", "biomesoplenty:woodland", "biomesoplenty:mystic_grove", "biomesoplenty:muskeg", "minecraft:sparse_jungle", "biomesoplenty:lavender_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:forested_field", "undergarden:dense_forest", "biomesoplenty:coniferous_forest", "biomesoplenty:ominous_woods", "biomesoplenty:redwood_forest", "minecraft:taiga", "biomesoplenty:floodplain", "minecraft:snowy_taiga", "minecraft:windswept_forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:boreal_forest", "biomesoplenty:orchard", "biomesoplenty:rainforest", "minecraft:old_growth_birch_forest", "biomesoplenty:fir_clearing", "undergarden:smogstem_forest", "minecraft:crimson_forest", "minecraft:swamp", "biomesoplenty:field", "minecraft:warped_forest", "undergarden:wigglewood_forest", "biomesoplenty:rainbow_hills", "biomesoplenty:maple_woods", "biomesoplenty:wetland", "biomesoplenty:highland_moor", "biomesoplenty:seasonal_forest", "biomesoplenty:jade_cliffs", "biomesoplenty:snowy_fir_clearing", "biomesoplenty:undergrowth", "minecraft:forest", "biomesoplenty:bayou", "biomesoplenty:marsh", "undergarden:gronglegrowth", "minecraft:old_growth_pine_taiga", "biomesoplenty:dead_forest", "minecraft:birch_forest", "minecraft:old_growth_spruce_taiga", "biomesoplenty:old_growth_dead_forest", "biomesoplenty:old_growth_woodland", "biomesoplenty:pumpkin_patch"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["biomesoplenty:cherry_blossom_grove", "biomesoplenty:orchard", "biomesoplenty:snowy_maple_woods", "biomesoplenty:bamboo_grove", "biomesoplenty:rainforest", "minecraft:old_growth_birch_forest", "biomesoplenty:fir_clearing", "minecraft:flower_forest", "minecraft:dark_forest", "minecraft:grove", "biomesoplenty:field", "biomesoplenty:woodland", "biomesoplenty:rainbow_hills", "biomesoplenty:maple_woods", "biomesoplenty:mystic_grove", "minecraft:sparse_jungle", "biomesoplenty:wetland", "biomesoplenty:lavender_forest", "biomesoplenty:seasonal_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:forested_field", "biomesoplenty:jade_cliffs", "biomesoplenty:snowy_fir_clearing", "minecraft:forest", "biomesoplenty:coniferous_forest", "biomesoplenty:ominous_woods", "minecraft:old_growth_pine_taiga", "biomesoplenty:dead_forest", "biomesoplenty:redwood_forest", "minecraft:birch_forest", "minecraft:taiga", "minecraft:old_growth_spruce_taiga", "minecraft:snowy_taiga", "minecraft:windswept_forest", "biomesoplenty:old_growth_dead_forest", "biomesoplenty:old_growth_woodland", "biomesoplenty:mediterranean_forest", "biomesoplenty:pumpkin_patch", "biomesoplenty:boreal_forest"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 30
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["minecraft:jagged_peaks", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:lush_desert", "biomesoplenty:snowy_maple_woods", "biomesoplenty:bamboo_grove", "minecraft:jungle", "biomesoplenty:bog", "minecraft:flower_forest", "minecraft:dark_forest", "biomesoplenty:crag", "minecraft:grove", "biomesoplenty:lush_savanna", "biomesoplenty:woodland", "minecraft:stony_peaks", "minecraft:meadow", "biomesoplenty:mystic_grove", "biomesoplenty:tropics", "biomesoplenty:muskeg", "minecraft:sparse_jungle", "biomesoplenty:lavender_forest", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:forested_field", "biomesoplenty:volcano", "minecraft:savanna_plateau", "minecraft:snowy_plains", "biomesoplenty:highland", "biomesoplenty:volcanic_plains", "biomesoplenty:coniferous_forest", "biomesoplenty:ominous_woods", "biomesoplenty:redwood_forest", "minecraft:snowy_slopes", "biomesoplenty:dune_beach", "biomesoplenty:rocky_rainforest", "minecraft:bamboo_jungle", "biomesoplenty:wasteland", "minecraft:taiga", "biomesoplenty:floodplain", "minecraft:snowy_taiga", "biomesoplenty:rocky_shrubland", "minecraft:windswept_forest", "minecraft:snowy_beach", "biomesoplenty:mediterranean_forest", "minecraft:windswept_savanna", "biomesoplenty:boreal_forest", "biomesoplenty:orchard", "biomesoplenty:rainforest", "minecraft:old_growth_birch_forest", "biomesoplenty:fir_clearing", "biomesoplenty:wooded_wasteland", "minecraft:swamp", "minecraft:lush_caves", "biomesoplenty:field", "minecraft:windswept_gravelly_hills", "biomesoplenty:rainbow_hills", "biomesoplenty:maple_woods", "minecraft:beach", "minecraft:frozen_peaks", "biomesoplenty:wetland", "minecraft:windswept_hills", "biomesoplenty:highland_moor", "biomesoplenty:seasonal_forest", "biomesoplenty:fungal_jungle", "biomesoplenty:jade_cliffs", "biomesoplenty:snowy_fir_clearing", "biomesoplenty:lavender_field", "minecraft:forest", "biomesoplenty:bayou", "biomesoplenty:marsh", "minecraft:old_growth_pine_taiga", "biomesoplenty:dead_forest", "minecraft:birch_forest", "minecraft:wooded_badlands", "minecraft:old_growth_spruce_taiga", "minecraft:stony_shore", "biomesoplenty:clover_patch", "biomesoplenty:old_growth_dead_forest", "biomesoplenty:old_growth_woodland", "biomesoplenty:pumpkin_patch"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

